### ISSUE TITLE
Tracking Issue First Release

### ISSUE THREAD

**Issue by SJSeckmeyer** [QSTheory/fftarray#22]
This issue is for tracking and discussing all reviews and changes before our first release.

## Open issues and open pull requests
- [x] #97
- [x] #90
- [ ] #79
- [x] #78
- [x] #75
- [ ] #74 
- [x] #73 
- [x] #44 
- [x] https://github.com/QSTheory/matterwave/issues/3
- [x] #39
- [x] #35
  - [x] #17
- [x] #36
- [x] #33
- [x] #42
- [x] #1
- [x] #2
- [x] #15
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #30 
- [x] #31 
- [x] #51 
- [ ] #52
- [x] #40
- [x] #12
- [x] #65 
- [x]  #77
- [x] #84 
- [x] #86 
- [x] #134
- [ ] FFTArray implementation in internal dbg_tools package
    - dbg needs to be updated and rearchitectured
    - one idea was to implement a  __panel__ method for FFTArray
    - refer to https://github.com/QSTheory/matterwave/pull/5 for a 3d FFTArray panel plot
- [x] Examples
  - [ ] Checkout MATLAB fft examples, FFT interpolation, subpixel translation
  - [ ] Derivative via FFT
  - [ ] 2d example: calculate force field from 2d potential
  - [ ] Selection example, cut out interesting part of FFTarray to create new one
  - [ ] Image denoising, see https://scipy-lectures.org/intro/scipy/auto_examples/solutions/plot_fft_image_denoise.html
- [x] Collection of (unit) test ideas
