### ISSUE TITLE
Tracking Issue Design Discussions

### ISSUE THREAD

**Issue by SJSeckmeyer** [QSTheory/fftarray#41]
- [x] #80 
- [ ] Interaction with other array APIs
 - Unnamed tensors (e.g. `numpy`, `jax`, `pytorch): #37
 - Named tensors: #38
- [x] #18 
- [ ] Global defaults
 - probably stays as it is
 - tensor-lib
 - precision
 - device
- [ ] n or n-1, probably stays, should be documented well
- [ ] Documentation overall meta:
 - https://diataxis.fr/
 - https://github.com/NiklasRosenstein/pydoc-markdown + mdBook?
- [ ] Dependency support
 - python, jax, numpy, …
 - CI with all supported versions (python, numpy?, …), explodes fast
- Code Coverage to testing suite/CI?
- [x] #3 
- [ ] #14
- [ ] https://github.com/QSTheory/matterwave/issues/11

To investigate:
- [x] #43
